name: volunteer-platform
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.0
  - pandas=1.3.3
  - flask=2.0.1
  - pip
  - pip:
    - flask-cors==3.0.10
    - gunicorn==20.1.0
    - xlsxwriter==3.0.2