services:
  - type: web
    name: volunteer-platform
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin:/app/.local/bin